### ISSUE TITLE
can't run it

### ISSUE THREAD

**Issue by linkcell** [leoncvlt/loconotion#139]
installed all good, but when trying to run it...

```console
$ python loconotion community.toml 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "loconotion/__main__.py", line 4, in <module>
    import modules.main as main
  File "loconotion/modules/main.py", line 8, in <module>
    from .notionparser import Parser
  File "loconotion/modules/notionparser.py", line 580
    if not (custom_fonts := self.get_page_config(url).get("fonts", {})):
                         ^
SyntaxError: invalid syntax
```

any ideas?

**Comment by leoncvlt** [comment]
Seems like a problem with the `:=` operator, what version of Python are you using? That's supported since 3.8 if I'm not wrong

**Comment by linkcell** [comment]
yup, using python 3.7. can you make it compatible?
