### ISSUE TITLE
Installation error command and driver

### ISSUE THREAD

**Issue by ToledoNicola** [leoncvlt/loconotion#29]
after the installation the driver was not foud so i downloaded it and placed inside the loconotion folder
but i can't run the command for add it 
`nicolamac  loconotion % python loconotion --chromedriver ./chromedriver
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 165, in _run_module_as_main
    mod_name, loader, code, fname = _get_main_module_details(_Error)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 133, in _get_main_module_details
    return _get_module_details(main_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 281, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/Users/nicolatoledo/Personale/loconotion/loconotion/__main__.py", line 14
    log.critical(f"ModuleNotFoundError: {error}. have your installed the requirements?")
                                                                                      ^
SyntaxError: invalid syntax`

**Comment by leoncvlt** [comment]
First of all, the script is not compatible with Python 2.7 - I can see it's failing at printing an f string which suggests you to install the requirements

So, in order
- Install the latest Python 3.x
- Follow the "Installation & Requirements" section in the readme

**Comment by ToledoNicola** [comment]
hi, thanks 
i have the mac, i tried pip3 and pyton3 but it doesn't work, i saw that i need to create a virtual environment, but i am a front-end developer and i am not expert in pyton and command line

it would be great if you could do a more complete guide even for those like me who are not familiar with this environment, for setup everything  🙂 

my goal is to generate html pages from notion and then modify the code

**Comment by leoncvlt** [comment]
You can create a virtual environment at `.venv` by running `python -m venv .venv`, and then activate it with `source .venv/bin/activate`

More info at:
- https://docs.python.org/3/tutorial/venv.html
- https://docs.python.org/3/library/venv.html

Also in your case I recommend going through the "Getting started" section here https://docs.python-guide.org/
