### ISSUE TITLE
Crash on tables explort

### ISSUE THREAD

**Issue by dansteingart** [leoncvlt/loconotion#4]
Upon trying to export the following page

https://www.notion.so/ceecnyc/Group-Members-c2858b83c7194a49ab527dfa4191b749

I'm getting this error

```
[22:35:46] ERROR Timeout waiting for the 'open' button to appear for row in table with block id 6bc9d731-73e1-4ef3-bb26-0918b4b8647b
Traceback (most recent call last):
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "loconotion/__main__.py", line 138, in <module>
    main()
  File "loconotion/__main__.py", line 117, in main
    Parser(config=config, args=vars(args))
  File "loconotion/notionparser.py", line 85, in __init__
    self.run(url)
  File "loconotion/notionparser.py", line 638, in run
    tot_processed_pages = self.parse_page(url)
  File "loconotion/notionparser.py", line 629, in parse_page
    self.parse_page(
  File "loconotion/notionparser.py", line 486, in parse_page
    table_row_href = self.driver.find_element_by_css_selector(
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div[data-block-id='6bc9d731-73e1-4ef3-bb26-0918b4b8647b'] > div > a"}
  (Session info: headless chrome=85.0.4183.102)
```
I thought it was because the table entry pages were empty, but even when I put text in the table pages it still throws this error.

(in any case thank you for a wonderful project!)

**Comment by leoncvlt** [comment]
I'll give this a proper test later, but I noticed that the second table takes its sweet time to load. Have you tried increase the `--timeout` value? If you run the tool in `--non-headless` mode you should be able to check whether the table has indeed loaded by the time the error shows up.

**Comment by dansteingart** [comment]
Thanks! 

WRT `timeout=` I get this error now, looks like there's a casting problem internally

```
[08:30:06] INFO Initialising parser with simple page url
[08:30:06] INFO Setting output path to 'dist/ceecnyc/steingart-lab-at-columbia'

[08:30:07] INFO Initialising chromedriver at /Users/dan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/chromedriver_autoinstaller/85/chromedriver
[08:30:08] INFO Parsing page 'https://www.notion.so/ceecnyc/Steingart-Lab-At-Columbia-ef7252f023d4421c9926188b9c2167de'
Traceback (most recent call last):
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "loconotion/__main__.py", line 138, in <module>
    main()
  File "loconotion/__main__.py", line 117, in main
    Parser(config=config, args=vars(args))
  File "loconotion/notionparser.py", line 85, in __init__
    self.run(url)
  File "loconotion/notionparser.py", line 638, in run
    tot_processed_pages = self.parse_page(url)
  File "loconotion/notionparser.py", line 274, in parse_page
    time.sleep(self.args["timeout"])
```

When I edit `__main__.py``  so the default is `30` rather than `5` it still fails

```
dan@ein loconotion % python3 loconotion https://www.notion.so/ceecnyc/Steingart-Lab-At-Columbia-ef7252f023d4421c9926188b9c2167de 
[08:32:28] INFO Initialising parser with simple page url
[08:32:28] INFO Setting output path to 'dist/ceecnyc/steingart-lab-at-columbia'
[08:32:28] INFO Initialising chromedriver at /Users/dan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/chromedriver_autoinstaller/85/chromedriver
[08:32:30] INFO Parsing page 'https://www.notion.so/ceecnyc/Steingart-Lab-At-Columbia-ef7252f023d4421c9926188b9c2167de'
[08:33:03] INFO Exporting page 'https://www.notion.so/ceecnyc/Steingart-Lab-At-Columbia-ef7252f023d4421c9926188b9c2167de' as 'index.html'
[08:33:03] INFO Parsing page 'https://www.notion.so/Group-Members-c2858b83c7194a49ab527dfa4191b749'
[08:33:42] ERROR Timeout waiting for the 'open' button to appear for row in table with block id 6bc9d731-73e1-4ef3-bb26-0918b4b8647b
Traceback (most recent call last):
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "loconotion/__main__.py", line 138, in <module>
    main()
  File "loconotion/__main__.py", line 117, in main
    Parser(config=config, args=vars(args))
  File "loconotion/notionparser.py", line 85, in __init__
    self.run(url)
  File "loconotion/notionparser.py", line 638, in run
    tot_processed_pages = self.parse_page(url)
  File "loconotion/notionparser.py", line 629, in parse_page
    self.parse_page(
  File "loconotion/notionparser.py", line 486, in parse_page
    table_row_href = self.driver.find_element_by_css_selector(
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/dan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div[data-block-id='6bc9d731-73e1-4ef3-bb26-0918b4b8647b'] > div > a"}
  (Session info: headless chrome=85.0.4183.102)

```

**Comment by podivilov** [comment]
Same problem here.

`root@msk-1:~/loconotion# python3 loconotion https://www.notion.so/podivilov/7503e30859b149a695d43900a0cef820 --chromedriver chromedriver -v
[05:15:28] INFO Initialising parser with simple page url
[05:15:28] INFO Setting output path to 'dist/podivilov/7503e30859b149a695d43900a0cef820'
[05:15:28] INFO Initialising chromedriver at chromedriver
[05:15:31] INFO Parsing page 'https://www.notion.so/podivilov/7503e30859b149a695d43900a0cef820'
[05:15:31] DEBUG Using page config: {}
[05:15:39] DEBUG Waiting for page content to load (pending blocks: 0, loading spinners: 0, loaded scrollers: 6 / 6)
[05:15:39] DEBUG Scrolling to bottom of notion-scroller (height: 4099)
[05:15:59] DEBUG New notion-scroller height after timeout is: 6137
[05:16:19] DEBUG New notion-scroller height after timeout is: 6137
[05:16:19] DEBUG Opening 3 new toggle blocks in the page
[05:16:20] DEBUG Waiting for toggle block to load (pending blocks: 3, loaders: 0)
[05:16:20] DEBUG Waiting for toggle block to load (pending blocks: 0, loaders: 0)
[05:16:21] DEBUG Waiting for toggle block to load (pending blocks: 3, loaders: 0)
[05:16:22] DEBUG Waiting for toggle block to load (pending blocks: 0, loaders: 0)
[05:16:22] DEBUG Waiting for toggle block to load (pending blocks: 1, loaders: 0)
[05:16:22] DEBUG Waiting for toggle block to load (pending blocks: 0, loaders: 0)
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F1ae1510c-da38-4c5c-aa3d-28eeb5a763fd%2Favatar.png?table=block&id=7503e308-59b1-49a6-95d4-3900a0cef820&width=40&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fwww.notion.so%2Fimages%2Fpage-cover%2Fmet_bruegel_1565.jpg?table=block&id=7503e308-59b1-49a6-95d4-3900a0cef820&width=3840&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F1ae1510c-da38-4c5c-aa3d-28eeb5a763fd%2Favatar.png?table=block&id=7503e308-59b1-49a6-95d4-3900a0cef820&width=250&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F0fdaf28b-26d5-4cd3-ad3f-60b5297ca0ec%2Fdribbble-icon-1-logo-png-transparent.png?table=block&id=53fc36fc-eee8-4fec-b64c-4e4d40d5a2c4&width=40&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F7d3c577c-519e-4fb6-9a25-0c674871eced%2F098a47681bb053fa476a97c5b5692a05.png?table=block&id=40869ac9-05eb-478c-abf3-0fbdbfe74f95&width=40&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F21bc310c-f407-42dd-834e-495bbee6df13%2Fday009.png?table=block&id=d8fdd472-80bc-4f2b-b287-cf30d949a88c&width=520&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F919f9be0-f6a2-4fce-8dc3-6630dfbfa9eb%2FDaily_UI._Day_8._404_Page.png?table=block&id=ea86a404-2029-437f-8adf-46af6e591dd5&width=520&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F3ac5d88a-37f0-4e89-8b05-385ae75768c0%2FDaily_UI._Day_7._Settings._.__2.png?table=block&id=68f9970c-dfcb-4559-8e25-dbf9d8aa74c1&width=520&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F9687c65e-da49-4826-bf8c-c85990241320%2Fday003.png?table=block&id=b4d73fc9-5300-4f23-8c42-4b0c588c81ea&width=520&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F8fed3728-60c9-4b98-bbf2-27295b8ea32c%2Fday012.png?table=block&id=b4c2d0db-5c74-4c56-bef0-eb6f6f11aa19&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F5d435614-1a00-4da7-940c-142631e55008%2Fday011.png?table=block&id=0234dc7a-74dd-4dc0-a83a-68170ba97e31&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fb9db8841-cbfc-4293-92ed-9efaffda6698%2Fday010.png?table=block&id=a79d06a3-6fd1-4a5c-a478-cb91f9392287&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F9c98ec17-368b-4c39-aaa0-c204e8de08d8%2FDaily_UI._Day_6._User_Profile._.__.png?table=block&id=cc883d29-98e6-4f88-b992-7d7334b7de64&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Ff4aaa9c3-80bc-44a4-bdb8-3c0e9ac798f6%2Fendend.png?table=block&id=fd50fce7-4ffe-49c9-96a3-bbc6e1b6d696&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F9515f584-a5c5-4f54-b442-c08cbcec6109%2Fday005.png?table=block&id=38c72b16-a40d-4c5a-9600-fe2f7910a86a&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F3869922d-605c-4a83-9c55-55163e863d10%2FDay_2._Credit_Card_Checkout.png?table=block&id=d1431756-5e7f-49ee-bf13-e3f67d86b236&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F680ff32e-d1c7-4064-8bc3-93c668790d82%2Fday001.png?table=block&id=d0d14188-298b-41c6-a742-c5ee1547da3c&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F16a328be-877e-42e6-b441-cd9a052e7b2b%2F600px-Telegram_logo.svg.png?table=block&id=212bfb34-8b41-414f-a52e-c96bd272ef99&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F2e19e5e7-817d-453a-85ae-a39ecf446290%2F1478241.png?table=block&id=046158e2-316d-4f1b-969c-fb31c53276d4&width=40&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F8805787e-68bb-4620-8d16-28390adf4559%2Ff_logo_RGB-Hex-Blue_512.png?table=block&id=f4afda46-191e-4245-8c37-d8b581a6ddb7&width=40&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fc76e7d22-07d0-41ec-9df6-e424dc8bc1bd%2FGroup_10.png?table=block&id=478fb932-b666-47d1-85ad-51569478c993&width=40&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fd0108093-f2bb-4464-a6e4-de0bbbb33538%2Finput-symbol-for-numbers_1f522.png?table=block&id=2f014c54-4fa8-4a2a-8579-f0106f54e7bd&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fd913fd13-a9bf-4905-9fea-bc08755623cd%2Fface-with-monocle_1f9d0.png?table=block&id=6b158938-8e21-4e19-ac16-8658ef467e7f&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fc27f3cf4-de56-4e03-b60b-2ee0ddf0904c%2Fclock-face-four-oclock_1f553.png?table=block&id=9a6e1357-f082-431f-ab75-53fadc49081e&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F373ef9e1-bc37-4233-82b3-ab7099cb67e6%2Feyes_1f440.png?table=block&id=b0ee43ac-1c03-4fbd-bb41-369dbb9a3e77&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fc89cce6b-c1b9-4818-aa6d-28cba7bd8dc1%2Fflag-for-united-states_1f1fa-1f1f8.png?table=block&id=e1604a45-38d4-44bd-a8f3-6c6f0a82052b&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F7fe0af78-5604-45c4-be8a-c024623e1dc5%2Fheavy-black-heart_2764.png?table=block&id=27acc8a8-5c4f-4383-8c76-b430504ccd12&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fd6e9e8af-d300-4e4f-a5a5-678145490c45%2Fsquared-new_1f195.png?table=block&id=1609096b-ef1e-436e-b03a-7af65caf802f&width=360&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F671ec81b-c170-4dc2-bdab-4b818906a89c%2Fios-a62dfc8fe7.png?table=block&id=73c6a7b7-5279-40c7-be14-f4cd3e20ea87&width=40&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F98fb4679-f41c-45e4-9e47-886dd8bec2ae%2F1200px-Spotify_logo_without_text.svg.png?table=block&id=d4f2b0d6-feb7-42ed-824d-bbbdb17a587d&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F7caaceca-a827-496e-8472-2e145055361a%2F647px-Apple_logo_black.svg.png?table=block&id=691ad916-d11d-4483-804b-9e30c3487b9c&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F7c464a3f-ac53-4ec7-b97e-f2fc431e1498%2FKak-dobavit-muzyiku-v-YAndeks.Muzyika.png?table=block&id=308b66bb-9934-40f3-be16-9936f357b4d9&width=40&userId=&cache=v2' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/images/twitter-emoji-spritesheet-64.png' was already downloaded
[05:16:23] DEBUG 'https://www.notion.so/print.b31f28aa.css' was already downloaded
[05:16:24] DEBUG 'https://www.notion.so/app-b1143cccdef6c905a0c7.css' was already downloaded
[05:16:24] DEBUG 'https://www.notion.so/lyon-text-regular-3be84b20b1d9ff1e3456b0a220ae449b.woff' was already downloaded
[05:16:24] DEBUG 'https://www.notion.so/lyon-text-regular-italic-437d32a42fc5b8268bb4a1e0cc8b363f.woff' was already downloaded
[05:16:24] DEBUG 'https://www.notion.so/lyon-text-semibold-acb7f110189034ff6a1afa4b730be0ed.woff' was already downloaded[05:16:24] DEBUG 'https://www.notion.so/lyon-text-semibold-italic-1f81a2f93060f05edd7f078ac91f25e6.woff' was already downloaded
[05:16:24] DEBUG 'https://www.notion.so/iawriter-mono-regular-4b73d071988a4f1cd2283524716ad970.woff' was already downloaded
[05:16:24] DEBUG 'https://www.notion.so/iawriter-mono-italic-d5d3224c1377168e261efc6aa0ce89c6.woff' was already downloaded
[05:16:24] DEBUG 'https://www.notion.so/iawriter-mono-bold-eb96a5e539892d26cf8b0cb2367e3580.woff' was already downloaded[05:16:24] DEBUG 'https://www.notion.so/iawriter-mono-bold-italic-743b231fa82483406c79a00fa1f12fe8.woff' was already downloaded
[05:16:24] DEBUG 'https://www.notion.so/inter-ui-regular-3ae6a7d3890c33d857fc00bd2e4c4820.woff' was already downloaded
[05:16:24] DEBUG 'https://www.notion.so/inter-ui-medium-95b8a98959d1af9ab432d7ffe295ef94.woff' was already downloaded
[05:16:24] DEBUG 'https://www.notion.so/inter-ui-semibold-19b57197b819695d334b9961ee41910e.woff' was already downloaded
[05:16:24] DEBUG 'https://www.notion.so/inter-ui-bold-001893789f7f342b520f29ac8af7d6ca.woff' was already downloaded
[05:16:24] DEBUG 'https://www.notion.so/permanent-marker-a6d62939e7c920a184ddddcf4149e62c.woff' was already downloaded
[05:16:30] ERROR Timeout waiting for the 'open' button to appear for row in table with block id 1452e2ef-d338-410b-ade5-6745f188d8ae
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "loconotion/__main__.py", line 138, in <module>
    main()
  File "loconotion/__main__.py", line 117, in main
    Parser(config=config, args=vars(args))
  File "loconotion/notionparser.py", line 85, in __init__
    self.run(url)
  File "loconotion/notionparser.py", line 640, in run
    tot_processed_pages = self.parse_page(url)
  File "loconotion/notionparser.py", line 488, in parse_page
    table_row_href = self.driver.find_element_by_css_selector(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div[data-block-id='1452e2ef-d338-410b-ade5-6745f188d8ae'] > div > a"}
  (Session info: headless chrome=85.0.4183.121)`

**Comment by leoncvlt** [comment]
I revised the table parsing method in the latest commit b1705ed7995c3415f92db53c4c3fdc200f75f667 - should have fixed this - give it a shot!

**Comment by dansteingart** [comment]
you did it! thanks!
