### ISSUE TITLE
Crash when parsing toggle blocks

### ISSUE THREAD

**Issue by Pz3r** [leoncvlt/loconotion#42]
I already tried increasing the timeout, however it keeps crashing at the exact same page. 

After a few timeout messages: 
`[16:52:31] WARNING Timeout waiting for toggle block to open. Likely it's already open, but doesn't hurt to check.`

I finally get:
`
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.9.2/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/.pyenv/versions/3.9.2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/loconotion/loconotion/__main__.py", line 144, in <module>
    main()
  File "/home/ubuntu/loconotion/loconotion/__main__.py", line 123, in main
    Parser(config=config, args=vars(args))
  File "/home/ubuntu/loconotion/loconotion/notionparser.py", line 85, in __init__
    self.run(url)
  File "/home/ubuntu/loconotion/loconotion/notionparser.py", line 658, in run
    tot_processed_pages = self.parse_page(url)
  File "/home/ubuntu/loconotion/loconotion/notionparser.py", line 645, in parse_page
    self.parse_page(
  File "/home/ubuntu/loconotion/loconotion/notionparser.py", line 645, in parse_page
    self.parse_page(
  File "/home/ubuntu/loconotion/loconotion/notionparser.py", line 645, in parse_page
    self.parse_page(
  [Previous line repeated 7 more times]
  File "/home/ubuntu/loconotion/loconotion/notionparser.py", line 336, in parse_page
    open_toggle_blocks(self.args["timeout"])
  File "/home/ubuntu/loconotion/loconotion/notionparser.py", line 301, in open_toggle_blocks
    toggle_button = toggle_block.find_element_by_css_selector(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/loconotion-IMDcpsi3-py3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 430, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/loconotion-IMDcpsi3-py3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/loconotion-IMDcpsi3-py3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/loconotion-IMDcpsi3-py3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/loconotion-IMDcpsi3-py3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: headless chrome=89.0.4389.90)
`

**Comment by leoncvlt** [comment]
Ha, to be honest you did test on probably the heaviest Notion page in the whole universe...

**Comment by Pz3r** [comment]
Now that you mention it I don't even know why that page is being parsed. It is not a page under the root I used.

**Comment by leoncvlt** [comment]
That's curious, I assume there's a link to that page hidden somewhere in your source?

**Comment by Pz3r** [comment]
So it took me a while but I think I found the cause. It is not a direct link to https://www.notion.so/What-s-New-157765353f2c4705bd45474e5ba8b46c the thing that is getting the parser misdirected is a "This image couldn't be loaded" error in one of the pages: 
![Screen Shot 2021-03-26 at 17 15 27](https://user-images.githubusercontent.com/782725/112701669-e4175c80-8e56-11eb-9fd1-8e6e45d106be.png)

As soon as the parser gets to that part of the page it then goes to: https://www.notion.so/Images-83601023414740ef9c79c23c64f80c6b and from there it enters into the rabbit hole of official notion pages hehe.

The html code from that error element is this one: 

```
<div style="width: 100%; max-width: 945px; align-self: center; margin-top: 0.5em; margin-bottom: 0.5em;" data-block-id="2fa8f291-46bc-4949-b569-3b74647ae81f" class="notion-selectable notion-image-block">
    <div>
        <div style="display: flex;">
            <div class="notion-cursor-default" style="position: relative; overflow: hidden; flex-grow: 1;">
                <div style="position: relative; cursor: pointer;">
                    <div style="height: 100%; width: 100%;"><img style="display: block; object-fit: cover; border-radius: 1px; background: white none repeat scroll 0% 0%; width: 100%; pointer-events: auto;" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"></div>
                    <div style="background: rgb(242, 241, 238) none repeat scroll 0% 0%; cursor: default; position: absolute; inset: 0px; display: flex; place-content: center; align-items: center; padding: 0.5em 1em; text-align: center; flex-direction: column; overflow: hidden;"><svg viewBox="0 0 32 32" style="width: 48px; height: 48px; display: block; fill: rgba(55, 53, 47, 0.4); flex-shrink: 0; backface-visibility: hidden; margin: 0px 0px 14px;" class="imageError"><path d="M6.39515 31.0485c3.44161 0 6.29115-2.8495 6.29115-6.2911 0-3.4355-2.8557-6.2912-6.29732-6.2912-3.43544 0-6.28495 2.8557-6.28495 6.2912 0 3.4416 2.85568 6.2911 6.29112 6.2911zm-.00617-5.366c-.32689 0-.50575-.1912-.51809-.5181l-.08635-3.0468c-.01233-.3393.24671-.5798.59828-.5798.34539 0 .61677.2467.60444.5859l-.09252 3.0407c-.01233.3331-.1912.5181-.50576.5181zm0 2.2698c-.35773 0-.69078-.2838-.69078-.6662s.32689-.6661.69078-.6661c.3639 0 .69079.2776.69079.6661 0 .3886-.33305.6662-.69079.6662z"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M4 17.5539V3h26v26H12.6862c.4113-.6095.7364-1.282.9578-2H28v-4H13.7749c-.1687-.7106-.4373-1.3825-.7902-2H28V5H6v12.1798c-.69548.0352-1.36626.164-2 .3741zM11.3329 19c-.6875-.5905-1.48192-1.0601-2.35027-1.3757L13 12l2 1 5-5 6 11H11.3329zM12 9c0 1.104-.896 2-2 2s-2-.896-2-2 .896-2 2-2 2 .896 2 2zm3.395 6.434l-1.76-.881L11.887 17h10.744l-3.107-5.695-4.129 4.129z"></path></svg>
                        <div style="font-size: 14px; line-height: 20px; color: rgba(55, 53, 47, 0.6); margin: 0px 0px 14px;">
                            <div style="display: block;">This image couldn't be loaded.</div><a href="https://www.notion.so/83601023414740ef9c79c23c64f80c6b#06dcdd8d490b470583ea6ebf44ad9e5b" target="_blank" rel="noopener noreferrer" style="display: inline; text-decoration: none; user-select: none; cursor: auto; color: inherit; pointer-events: auto; border-bottom: 1px solid rgba(55, 53, 47, 0.4);">Learn more</a></div>
                        <div style="font-size: 12px; line-height: 16px; color: rgba(55, 53, 47, 0.4); white-space: nowrap; overflow: hidden; text-overflow: ellipsis;"></div>
                    </div>
                </div>
                <div style="display: block; height: 100%;" class="notion-block-resizer">
                    <div style="position: absolute; pointer-events: none; display: flex; align-items: center; justify-content: center; left: 0px; top: 0px; z-index: 1; height: 100%; width: 15px; cursor: col-resize;">
                        <div style="opacity: 0; transition: opacity 300ms ease-in 0s; border-radius: 20px; background: rgba(15, 15, 15, 0.6) none repeat scroll 0% 0%; border: 1px solid rgba(255, 255, 255, 0.9); width: 6px; height: 48px; max-height: 50%;"></div>
                    </div>
                </div>
                <div style="display: block; height: 100%;" class="notion-block-resizer">
                    <div style="position: absolute; pointer-events: none; display: flex; align-items: center; justify-content: center; right: 0px; top: 0px; z-index: 1; height: 100%; width: 15px; cursor: col-resize;">
                        <div style="opacity: 0; transition: opacity 300ms ease-in 0s; border-radius: 20px; background: rgba(15, 15, 15, 0.6) none repeat scroll 0% 0%; border: 1px solid rgba(255, 255, 255, 0.9); width: 6px; height: 48px; max-height: 50%;"></div>
                    </div>
                </div>
                <div style="position: absolute; top: 4px; right: 4px; border-radius: 3px; color: white; fill: white; font-size: 11.5px; background: rgba(0, 0, 0, 0.6) none repeat scroll 0% 0%; display: flex; white-space: nowrap; max-width: calc(100% - 16px); overflow: hidden; pointer-events: none; opacity: 0; transition: opacity 300ms ease-in 0s; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, &quot;Apple Color Emoji&quot;, Arial, sans-serif, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; z-index: 2;">
                    <div style="user-select: none; transition: background 20ms ease-in 0s; cursor: pointer; display: flex; align-items: center; padding: 4px 6px; border-right: 1px solid rgba(255, 255, 255, 0.2);" class="" role="button" tabindex="0"><svg viewBox="0 0 16 16" style="width: 12px; height: 12px; display: block; fill: white; flex-shrink: 0; backface-visibility: hidden; margin-right: 0px;" class="speechBubble"><path d="M4.32 15.424c.39 0 .677-.192 1.149-.609l2.344-2.064h4.116c2.057 0 3.213-1.19 3.213-3.22V4.22c0-2.03-1.156-3.22-3.213-3.22H3.213C1.163 1 0 2.19 0 4.22V9.53c0 2.037 1.196 3.22 3.165 3.22h.28v1.675c0 .608.322.998.875.998zm.342-1.531v-1.949c0-.403-.178-.56-.56-.56H3.26c-1.285 0-1.9-.65-1.9-1.894V4.26c0-1.243.615-1.893 1.9-1.893h8.627c1.278 0 1.893.65 1.893 1.894v5.23c0 1.243-.615 1.893-1.893 1.893h-4.15c-.417 0-.622.068-.909.369l-2.167 2.14z"></path></svg></div>
                    <div style="user-select: none; transition: background 20ms ease-in 0s; cursor: pointer; display: flex; align-items: center; padding: 4px 6px; border-right: 1px solid rgba(255, 255, 255, 0.2);" class="" role="button" tabindex="0">Caption</div>
                    <div style="user-select: none; transition: background 20ms ease-in 0s; cursor: pointer; display: flex; align-items: center; padding: 4px 6px; border-right: 1px solid rgba(255, 255, 255, 0.2);" class="" role="button" tabindex="0">Original</div>
                    <div style="user-select: none; transition: background 20ms ease-in 0s; cursor: pointer; display: flex; align-items: center; justify-content: center; flex-shrink: 0; width: 24px; height: 24px; border-radius: 3px; fill: rgba(55, 53, 47, 0.4);" class="" role="button" tabindex="0"><svg viewBox="0 0 13 3" style="width: 14px; height: 14px; display: block; fill: white; flex-shrink: 0; backface-visibility: hidden;" class="dots"><g> <path d="M3,1.5A1.5,1.5,0,1,1,1.5,0,1.5,1.5,0,0,1,3,1.5Z"></path> <path d="M8,1.5A1.5,1.5,0,1,1,6.5,0,1.5,1.5,0,0,1,8,1.5Z"></path> <path d="M13,1.5A1.5,1.5,0,1,1,11.5,0,1.5,1.5,0,0,1,13,1.5Z"></path> </g></svg></div>
                </div>
            </div>
        </div>
    </div>
</div>
```

**Comment by leoncvlt** [comment]
Ha, that's a beautiful edge case. Will see if we can add an exclusion list for stuff like that "learn more" link!

**Comment by Pz3r** [comment]
That would be great! By the way the "learn more" link is also present in other type of _broken_ media such as videos.
