### ISSUE TITLE
Chromedriver Crashes when Program is run outside of loconotion folder

### ISSUE THREAD

**Issue by RohanRaman-SB** [leoncvlt/loconotion#61]
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/loconotion/loconotion/__main__.py", line 144, in <module>
    main()
  File "/home/ubuntu/loconotion/loconotion/__main__.py", line 134, in main
    Parser(config=parsed_config, args=vars(args))
  File "/home/ubuntu/loconotion/loconotion/notionparser.py", line 84, in __init__
    self.driver = self.init_chromedriver()
  File "/home/ubuntu/loconotion/loconotion/notionparser.py", line 240, in init_chromedriver
    return webdriver.Chrome(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /usr/bin/chromedriver unexpectedly exited. Status code was: 1
```
I ran my script from the home folder, and I got this error. When I run the script (that exists in the home folder) inside the loconotion directory, it runs fine. What's going on?

**Comment by sueszli** [comment]
I was able to reproduce and resolve this bug by using the `webdriver_manager.chrome` dependency which automatically sets the correct relative path to the driver executable, no matter what directory you are in.

You can check it out here: https://github.com/sueszli/notionSnapshot/blob/master/notionsnapshot/driver.py
